<?php
/**
 * Copyright since 2022 Younited Credit
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to tech@202-ecommerce.com so we can send you a copy immediately.
 *
 * @author     202 ecommerce <tech@202-ecommerce.com>
 * @copyright 2022 Younited Credit
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var $block \YounitedCredit\YounitedPay\Block\Product\Widget
 */
?>
<?php $product = $block->getProduct() ?>
<?php if ($block->isEnabled() && $product && $product->getId() && $product->getTypeId() != 'grouped') : ?>
    <?php $installments = $block->getInstallments($product) ?>
    <?php if (!is_array($installments) && $block->isDevMode()) : ?>
        <div class="yp-error-notice"><?= $installments ?></div>
    <?php elseif (!empty($installments)) : ?>
        <?php $defaultMaturity = 0 ?>
        <?php $defaultInstallment = 0 ?>
        <div class="younitedpay-widget-root" id="yp-widget" data-price="<?= $block->getProductPrice($product) ?>"
             data-type="<?= $product->getTypeId() ?>">
            <div id="younited_block">
                <img src="<?= $block->getImageSrc('logo-younitedpay-btn.png') ?>" alt="<?= __("Younited Pay") ?>">
                <div id="yp-current-maturities">
                    <?php $i = 0;
                    foreach ($installments as $installment => $amount) : ?>
                        <?php $defaultMaturity = ($i == 0) ? $amount['monthlyInstallmentAmount'] : $defaultMaturity; ?>
                        <?php $defaultInstallment = ($i == 0) ? $installment : $defaultInstallment; ?>
                        <div class="maturity_installment <?= ($i == 0) ? 'selected' : '' ?>"
                             id="maturity_installment<?= $installment ?>" data-key="<?= $installment ?>"
                             data-maturity="<?= $amount['monthlyInstallmentAmount'] ?>">
                            <span><?= $installment ?>x</span>
                        </div>
                        <?php $i++; endforeach; ?>
                </div>
                <div class="yp-current-installment">
                    <b><span><span id="yp-maturity"><?= $defaultMaturity ?></span>€</span></b>
                    <span id="yp-installment">x<?= $defaultInstallment ?></span>
                </div>
            </div>
            <div id="younited_popupzone" style="display:none;">
                <div class="popup-content">
                    <button id="yp-close-popup">x</button>
                    <div class="yp-left">
                        <img class="yp-popup-logo" src="<?= $block->getImageSrc('logo-younitedpay.png') ?>"
                             alt="youpay">
                        <div class="yp-left-title">
                            <h3><?= __("Simple") ?>.</h3>
                            <h3><?= __("Instant") ?>.</h3>
                            <h3><?= __("Secured") ?>.</h3>
                        </div>
                        <div class="yp-text">
                            <?= __("Younited, it's never been easier") ?><br>
                            <?= __("to pay in several times.") ?>
                        </div>
                        <div class="yp-link">
                            <?= __("Have a question? Visit our") ?> <a
                                    href="https://www.younited-credit.com/questions-reponses"
                                    target="_blank"><?= __("dedicated page") ?></a>
                        </div>
                        <div class="logo-cards">
                            <img src="<?= $block->getImageSrc('cb.png') ?>" alt="<?= __("Bank Card") ?>">
                            <img src="<?= $block->getImageSrc('visa.png') ?>" alt="<?= __("Visa") ?>">
                            <img src="<?= $block->getImageSrc('mastercard.png') ?>" alt="<?= __("Mastercard") ?>">
                        </div>
                    </div>
                    <div class="yp-right">
                        <h4>
                            <?= __("Your purchase for") ?> <span
                                    id="popup-maturity"><?= $defaultMaturity ?></span>€<?= __("/month with") ?><br>
                            <span class="yp-purple"><?= __("Younited Pay") ?></span>
                        </h4>
                        <ul id="yp-popup-maturities">
                            <?php $i = 0; ?>
                            <?php $defautAmount = []; ?>
                            <?php foreach ($installments as $installment => $amount) : ?>
                                <?php $defautAmount = ($i == 0) ? $amount : $defautAmount ?>
                                <li class="blocks_maturities_popup <?= ($i == 0) ? 'selected' : '' ?>"
                                    id="blocks_maturities_popup<?= $installment ?>"
                                    data-key="<?= $installment ?>"
                                    data-maturity="<?= $amount['monthlyInstallmentAmount'] ?>"
                                    data-amount="<?= $amount['requestedAmount'] ?>"
                                    data-percent="<?= $amount['annualPercentageRate'] ?>"
                                    data-debit="<?= $amount['annualDebitRate'] ?>"
                                    data-total="<?= $amount['creditTotalAmount'] ?>"
                                    data-interests="<?= $amount['interestsTotalAmount'] ?>">
                                    <span class=""><?= $installment ?> <?= __("months") ?></span>
                                </li>
                                <?php $i++; endforeach; ?>
                        </ul>

                        <p class="info-text">
                            <span class="yp-dark-purple"><?= __("Buy today and start paying") ?></span><br>
                            <span class="yp-purple"><?= __("in just 30 days!") ?></span>
                        </p>

                        <div class="yp-finance">
                            <div>
                                <p class="yp-dark-purple yp-font-normal"><?= __("Amount of financing") ?></p>
                                <p class="yp-dark-purple"><span id="yp-amount"><?= $amount['requestedAmount'] ?></span>
                                    €</p>
                            </div>
                            <div>
                                <p class="yp-dark-purple">+ <span
                                            class="yp-font-normal"><?= __("Payment cost") ?></span></p>
                                <p class="yp-dark-purple"><span
                                            id="yp-cost"><?= $amount['interestsTotalAmount'] ?></span> €</p>
                            </div>
                            <hr/>
                            <div>
                                <p class="yp-dark-purple">= <?= __("Total amount owed") ?></p>
                                <p class="yp-dark-purple"><span id="yp-total"><?= $amount['creditTotalAmount'] ?></span>
                                    €</p>
                            </div>
                        </div>

                        <div class="yp-tax">
                            <div><span class="yp-dark-purple"><?= __("Fixed APR") ?>:&nbsp;&nbsp;<span
                                            id="yp-percent"><?= $amount['annualPercentageRate'] * 100 ?></span> %</span>
                            </div>
                            <div><span class="yp-dark-purple"><?= __("Fixed borrowing rate") ?>:&nbsp;&nbsp;<span
                                            id="yp-debit"><?= $amount['annualDebitRate'] * 100 ?></span> %</span></div>
                        </div>

                        <div class="yp-engagement">
                            <?= __("A loan commits you and must<br>be repaid. Check yourability to<br>repay before commit yourself.") ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "*": {
                    "ypwidget" : {
                        "url": "<?= $block->getUrl('younited/ajax/maturity') ?>",
                        "loader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')); ?>",
                        "store": "<?= $block->getStoreCode() ?>"
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>


