<?php
/**
 * Copyright since 2022 Younited Credit
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to tech@202-ecommerce.com so we can send you a copy immediately.
 *
 * @author     202 ecommerce <tech@202-ecommerce.com>
 * @copyright 2022 Younited Credit
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var $block \YounitedCredit\YounitedPay\Block\Product\Widget
 */
?>
<?php $product = $block->getProduct() ?>
<?php if ($block->isEnabled() && $product && $product->getId() && $product->getTypeId() != 'grouped'): ?>
    <?php $installments = $block->getInstallments($product) ?>
    <?php $defaultMaturity = 0 ?>
    <?php $defaultInstallment = 0 ?>
    <div class="younitedpay-widget-root" id="yp-widget"
         data-price="<?= $block->escapeHtml($block->getWidgetProductPrice($product)) ?>"
         data-type="<?= $block->escapeHtml($product->getTypeId()) ?>"
        <?php if (empty($installments)): ?> style="display: none"<?php endif ?>>
        <div class="younited_block yp-pb-2 yp-pt-2 yp-my-2">
            <div class="yp-cursor-pointer yp-flex yp-flex-row yp-items-center yp-flex-wrap">
                <img class="yp-mb-2 yp-logo lazyloaded" src="<?= $block->escapeHtml($block->getImageSrc('logo-younitedpay.png')) ?>"
                    alt="<?= $block->escapeHtml(__("Younited Pay")) ?>">
                    <?php $i = 0; ?>
                    <?php foreach ($installments as $installment => $amount): ?>
                        <?php $defaultMaturity = ($i == 0) ? $amount['monthlyInstallmentAmount'] : $defaultMaturity; ?>
                        <?php $defaultInstallment = ($i == 0) ? $installment : $defaultInstallment; ?>
                        <?php $background_block = ($i == 0) ? ' yp-bg-black-btn' : ''; ?>
                        <span class="yp-flex yp-flex-row yp-space-x-1 yp-mx-2 yp-mb-1 maturity_installment maturity_installment<?php $i . $background_block; ?>"
                            data-key="<?= $i ?>"
                            data-maturity="<?= $block->escapeHtml($amount['monthlyInstallmentAmount']) ?>"
                            data-initamount="<?= $block->escapeHtml($amount['requestedAmount']) ?>"
                            data-taeg="<?= $block->escapeHtml($amount['annualPercentageRate']) ?>"
                            data-tdf="<?= $block->escapeHtml($amount['annualDebitRate']) ?>"
                            data-totalamount="<?= $block->escapeHtml($amount['creditTotalAmount']) ?>"
                            data-interesttotal="<?= $block->escapeHtml($amount['interestsTotalAmount']) ?>"
                        >
                            <span class="yp-inline-block yp-h-10">
                                <span class="yp-inline-block yp-transition-all yp-border-opacity-100 yp-h-10 
                                    blocks_maturity block_maturity<?= $i ?> yp-flex flexmiddle ">
                                    <span class="yp-flex flexmiddle yp-p-2 yp-rounded-sm yp-transition-colors 
                                    yp-duration-500 yp-select-none">
                                        <?= $block->escapeHtml($installment) ?>x
                                    </span>
                                </span>
                            </span>
                        </span> 
                        <?php $i++; ?>
                    <?php endforeach; ?>
            </div>
            <div class="yp-cursor-pointer yp-flex yp-flex-row yp-items-center yp-flex-wrap yp-text-xs yp-p-2 yp-pb-0">
                <a href="#younited_popupzone" id="yp-kml">
                    <p><?= __("Click to learn more") ?></p>
                </a>
            </div>
        </div>
        <div id="younited_popupzone" style="display:none;">
            <div class="popup-content">
                <button id="yp-close-popup">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="#1C1C1C" class="yp-close-black" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8.4 7L13.7 1.7C14.1 1.3 14.1 0.7 13.7 0.3C13.3 -0.1 12.7 -0.1 12.3 0.3L7 5.6L1.7 0.3C1.3 -0.1 0.7 -0.1 0.3 0.3C-0.1 0.7 -0.1 1.3 0.3 1.7L5.6 7L0.3 12.3C-0.1 12.7 -0.1 13.3 0.3 13.7C0.5 13.9 0.7 14 1 14C1.3 14 1.5 13.9 1.7 13.7L7 8.4L12.3 13.7C12.5 13.9 12.8 14 13 14C13.2 14 13.5 13.9 13.7 13.7C14.1 13.3 14.1 12.7 13.7 12.3L8.4 7Z"></path>
                </svg>
                </button>
                <div class="yp-left">
                    <div class="yp-left-title">
                        <span><?= $block->escapeHtml(__("Buy now and pay as you go")) ?></span>
                    </div>
                    <div class="yp-text yp-font-normal yp-pol-purpledark">
                        <span class="yp-step">
                            <span class="yp-linumber">1</span>
                            <span><?= __("At checkout step, select <b>Younited Pay</b>") ?></span>
                        </span>
                        <span class="yp-step">
                            <span class="yp-linumber">2</span>
                            <span><?= __("Choose the repayment <b>duration</b>") ?></span>
                        </span>
                        <span class="yp-step">
                            <span class="yp-linumber">3</span>
                            <span><?= __("<b>Simply</b> and <b>securely</b> connect your bank account") ?></span>
                        </span>
                        <span class="yp-step">
                            <span class="yp-linumber">4</span>
                            <span><?= __("Receive a response <b>within seconds</b>") ?></span>
                        </span>
                    </div>
                    <div class="yp-center">
                        <img class="yp-popup-logo" alt="youpay" src="<?= $block->escapeHtml($block->getImageSrc('logo-younitedpay.png')) ?>" />
                    </div>
                </div>
                <div class="yp-right">
                    <div class="yp-flex-grow">
                        <div class="yp-text-base yp-mt-4 yp-mb-5 yp-h4 yp-text-center">
                            <span data-bind="i18n: 'Start paying in just 30 days !'"></span>
                        </div>
                        <div class="yp-flex yp-justify-center yp-mt-6">
                            <?php $i = 0; ?>
                            <?php $defautAmount = [
                                'requestedAmount' => 0,
                                'interestsTotalAmount' => 0,
                                'creditTotalAmount' => 0,
                                'annualPercentageRate' => 0,
                                'annualDebitRate' => 0
                            ]; ?>
                            <?php foreach ($installments as $installment => $amount): ?>
                                <?php $defautAmount = ($i == 0) ? $amount : $defautAmount ?>
                                <?php $background_block = ($i == 0) ? ' yp-bg-black-btn' : ''; ?>
                                <span class="yp-flex yp-flex-row yp-space-x-1 yp-mx-2 yp-mb-1 maturity_installment maturity_installment<?php $i . $background_block ?>"
                                    data-key="<?= $i ?>"
                                    data-maturity="<?= $block->escapeHtml($amount['monthlyInstallmentAmount']) ?>"
                                    data-initamount="<?= $block->escapeHtml($amount['requestedAmount']) ?>"
                                    data-taeg="<?= $block->escapeHtml($amount['annualPercentageRate']) ?>"
                                    data-tdf="<?= $block->escapeHtml($amount['annualDebitRate']) ?>"
                                    data-totalamount="<?= $block->escapeHtml($amount['creditTotalAmount']) ?>"
                                    data-interesttotal="<?= $block->escapeHtml($amount['interestsTotalAmount']) ?>"
                                >
                                    <span class="yp-inline-block yp-h-10">
                                        <span class="yp-inline-block yp-transition-all yp-border-opacity-100 yp-h-10 
                                            blocks_maturity block_maturity<?= $i ?> yp-flex flexmiddle ">
                                            <span class="yp-flex flexmiddle yp-p-2 yp-rounded-sm yp-transition-colors 
                                            yp-duration-500 yp-select-none">
                                                <?= $block->escapeHtml($installment) ?>x
                                            </span>
                                        </span>
                                    </span>
                                </span> 
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </div>
                        <div class="yp-flex yp-justify-center yp-align-center yp-font-bold yp-text-md yp-font-family-rg yp-mt-6 yp-mb-3">
                            <span data-bind="i18n: 'Payment in'"></span>&nbsp;
                            <span class="yp-pol-purpledark yp-pol-purple">
                                <span data-bind="text: maturity.installment" class="yp-install-maturity-lite"></span>
                                <span data-bind="i18n: 'times'"></span>
                            </span>
                        </div>
                        <div class="yp-info-buy yp-flex yp-font-family-rg yp-mt-6 yp-justify-between yp-items-center">
                            <p class="yp-flex yp-items-center yp-weight600 yp-pol-purpledark yp-text-20">
                                <span data-bind="i18n: 'Your purchase for '"></span>&nbsp;
                                <span data-bind="text: maturity.monthlyInstallmentAmount" 
                                    class="yp-pol-purple yp-text-20 yp-font-bold yp-font-family-rg yp-install-amount"></span>&nbsp;&euro; / 
                                <span data-bind="i18n: 'months'"></span>
                            </p>
                        </div>

                        <div class="yp-border-prple yp-border-2 yp-p-3 yp-rounded-bg yp-mt-6">
                            <div class="yp-mb-8 yp-text-lg yp-pol-purpledark">
                                <div class="yp-flex yp-flex-row yp-justify-between yp-pol-purple yp-mb-2 yp-text-20 yp-weight600">
                                    <span><b><span data-bind="i18n: 'Total amount due'"></span></b></span>
                                    <span class="yp-mw85 yp-text-right">
                                        <span class="yp-total" data-bind="text: maturity.creditTotalAmount"></span>&nbsp;€
                                    </span>
                                </div>
                                <div class="yp-flex yp-flex-row yp-justify-between yp-mb-2">
                                    <p class="yp-pol-purpledark yp-font-normal">&nbsp;&nbsp;&nbsp;<span data-bind="i18n: 'Total credit amount'"></span></p>
                                    <p class="yp-weight600 yp-pol-purpledark yp-mw85 yp-text-right">
                                        <span class="yp-amount" data-bind="text: maturity.requestedAmount"></span>&nbsp;€
                                    </p>
                                </div>
                                <div class="yp-flex yp-flex-row yp-justify-between yp-pb-6">
                                    <p class="yp-pol-purpledark yp-font-normal">&nbsp;&nbsp;&nbsp;
                                        <span data-bind="i18n: 'Interest (excl. optional insurance)'"></span>
                                    </p>
                                    <p class="yp-weight600 yp-pol-purpledark yp-mw85 yp-text-right">
                                        <span class="yp-interest" data-bind="text: maturity.interestsTotalAmount"></span>&nbsp;€
                                    </p>
                                </div>
                            </div>
                            <div class="yp-mt-6 block_contents block_content_range">
                                <div class="yp-justify-between yp-flex yp-flex-row yp-mb-2 yp-text-20">
                                    <span class="yp-weight600 yp-pol-purpledark" data-bind="i18n: 'Fixed APR'">
                                        <!-- ko if: ( maturity.locale != "es_ES" ) -->
                                            <br><span data-bind="i18n: '(excluding optional insurance)'"></span>
                                        <!-- /ko -->
                                    </span>
                                    <span class="yp-weight600 yp-pol-purpledark yp-mw85 yp-text-right">
                                        <span class="yp-taeg" data-bind="text: maturity.annualPercentageRate"></span> %
                                    </span>
                                </div>
                                <div class="yp-justify-between yp-flex yp-flex-row yp-mb-2 yp-pol-purpledark yp-font-normal">
                                    <span data-bind="i18n: 'Fixed lending rate'"></span>
                                    <span class="yp-weight600 yp-mw85 yp-text-right">
                                        <span class="yp-tdf" data-bind="text: maturity.annualDebitRate"></span> %
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="yp-text-responsabilities yp-my-4">
                            <p class="yp-weight600 yp-pol-purpledark yp-text-20"
                                data-bind="i18n: 'Taking out a loan is a commitment with an obligation of repayment. Verify your ability to repay the loan before committing.'">
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
            {
                "*": {
                    "ypwidget" : {
                        "url": "<?= $block->escapeUrl($block->getUrl('younited/ajax/maturity')) ?>",
                        "loader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')); ?>",
                        "store": "<?= $block->escapeHtml($block->getStoreCode()) ?>"
                    }
                }
            }

    </script>
<?php endif; ?>


