<?php
/**
 * Copyright since 2022 Younited Credit
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to tech@202-ecommerce.com so we can send you a copy immediately.
 *
 * @author     202 ecommerce <tech@202-ecommerce.com>
 * @copyright 2022 Younited Credit
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */

/**
 * @var \YounitedCredit\YounitedPay\Block\Order\Info $block
 * @see \YounitedCredit\YounitedPay\Block\Order\Info
 */
$specificInfo = $block->getInfo()->getOrder()->getPayment()->getAdditionalInformation();
unset($specificInfo['method_title']);

$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><img src="<?= $block->getYpImage() ?>" alt="<?= /* @noEscape */ $title ?>" /></dt>
<?php if ($specificInfo) : ?>
    <dd class="content">
        <table class="data table">
            <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
            <?php foreach ($specificInfo as $label => $value) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__($label)) ?></th>
                    <td>
                        <?= /* @noEscape */ __(nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </dd>
<?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
