<?php
/**
 * Copyright since 2022 Younited Credit
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to tech@202-ecommerce.com so we can send you a copy immediately.
 *
 * @author     202 ecommerce <tech@202-ecommerce.com>
 * @copyright 2022 Younited Credit
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */

/**
 * @var \YounitedCredit\YounitedPay\Block\Order\Info $block
 * @see \YounitedCredit\YounitedPay\Block\Order\Info
 */
$specificInfo = $block->getSpecificInformation();
$additionalInfo = $block->getInfo()->getOrder()->getPayment()->getAdditionalInformation();
unset($additionalInfo['method_title']);

$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<img src="<?= $block->getYpImage() ?>" alt="<?= /* @noEscape */ $paymentTitle ?>" />

<?php if ($specificInfo) : ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($specificInfo as $label => $value) : ?>
        <tr>
            <th><?= $block->escapeHtml($label) ?>:</th>
            <td>
                <?= /* @noEscape */ __(nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray(__($value), true))))) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?php if ($additionalInfo) : ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($additionalInfo as $label => $value) : ?>
        <tr>
            <th><?= $block->escapeHtml(__($label)) ?>:</th>
            <td>
                <?= /* @noEscape */ __(nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))))) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
